spring:
  application:
    name: product-order-api

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order-stock-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: user_app
    password: "Java@1979"
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    out-of-order: false
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      "[hibernate.format_sql]": true
      "[hibernate.type.preferred_uuid_jdbc_type]": VARBINARY
    open-in-view: false

  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 10s
    socket-timeout: 60s

server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: always

logging:
  level:
    root: INFO
    "[org.springframework.web]": DEBUG
    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.type.descriptor.sql.BasicBinder]": TRACE
    "[br.com.marcos]": DEBUG
    "[org.apache.kafka]": WARN